# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetOutfit.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fGetOutfit.proto\"#\n\x0e\x43SGetOutfitReq\x12\x11\n\tAccountId\x18\x01 \x01(\x04\"L\n\x0e\x43SGetOutfitRes\x12\x17\n\x0fWeaponSkinShows\x18\x01 \x03(\x04\x12!\n\x0bProfileInfo\x18\x02 \x01(\x0b\x32\x0c.ProfileInfo\"\xc3\x01\n\x0bProfileInfo\x12\x13\n\x0b\x43haracterId\x18\x01 \x01(\x04\x12\x11\n\tSkinColor\x18\x03 \x01(\r\x12\x0f\n\x07\x43lothes\x18\x04 \x03(\x04\x12\x1f\n\x0e\x45quippedSkills\x18\x05 \x03(\x0b\x32\x07.Skills\x12\x17\n\nIsSelected\x18\x06 \x01(\x08H\x00\x88\x01\x01\x12\x1d\n\x10IsAwakenSelected\x18\x08 \x01(\x08H\x01\x88\x01\x01\x42\r\n\x0b_IsSelectedB\x13\n\x11_IsAwakenSelected\"9\n\x06Skills\x12\x13\n\x06SlotNo\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x0f\n\x07SkillId\x18\x02 \x01(\rB\t\n\x07_SlotNob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetOutfit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETOUTFITREQ']._serialized_start=19
  _globals['_CSGETOUTFITREQ']._serialized_end=54
  _globals['_CSGETOUTFITRES']._serialized_start=56
  _globals['_CSGETOUTFITRES']._serialized_end=132
  _globals['_PROFILEINFO']._serialized_start=135
  _globals['_PROFILEINFO']._serialized_end=330
  _globals['_SKILLS']._serialized_start=332
  _globals['_SKILLS']._serialized_end=389
# @@protoc_insertion_point(module_scope)